// Regenerates the Android home-screen widgets' palette variants.
//
//   flutter test tool/widget_palettes_test.dart
//
// Widgets are drawn by the launcher from Android resources, outside the
// Flutter engine, so they cannot read TideColors. Midnight's widgets are the
// hand-written files in android/app/src/main/res; every other palette gets a
// generated copy of each widget layout and drawable (`<name>_<palette id>`)
// pointing at its own colours in values/widget_palettes.xml. WidgetTheme.kt
// picks the copy for the palette the app last reported.
//
// Lives outside test/ for the same reason brand_assets_test.dart does: it
// writes into android/. Run it after changing a palette in
// lib/theme/tide_palette.dart or any widget layout or drawable, then commit
// what it wrote.
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tide/theme/tide_palette.dart';

const _res = 'android/app/src/main/res';

/// Written into every generated file, and the only thing that lets the tool
/// delete a file: a hand-written resource never carries it.
const _marker = 'Generated by tool/widget_palettes_test.dart';

/// The palette whose widgets are the hand-written originals.
const _original = TidePalettes.midnight;

/// The widget colours, derived from a palette's roles.
///
/// Midnight's are hand-tuned in values/colors.xml; these are the same
/// relationships expressed as arithmetic so a new palette needs no widget
/// work at all. Surfaces are steps from the card toward the ink rather than
/// the palette's own shoal, because on a light palette shoal is the same
/// white as the card and a ring track or an empty day would vanish.
Map<String, Color> _widgetColours(TidePalette p) {
  Color mix(Color a, Color b, double t) => Color.lerp(a, b, t)!;
  Color alpha(Color c, int a) => c.withAlpha(a);

  final cellEmpty = mix(p.shelf, p.bone, 0.08);
  final cellRest = mix(p.shelf, p.bone, 0.035);
  final shoal = mix(p.shelf, p.bone, 0.09);
  return {
    'ground': p.deepWater,
    'shelf': p.shelf,
    'shoal': shoal,
    'bone': p.bone,
    'silt': p.silt,
    'lantern': p.lantern,
    'on_lantern': p.onLantern,
    'coral': p.coral,
    'rest': alpha(p.bone, 0x0A),
    'flare': p.flare,
    'ember': p.ember,
    'card_edge': alpha(p.bone, p.isLight ? 0x24 : 0x14),
    'tile': mix(p.shelf, p.bone, 0.05),
    'lantern_soft': alpha(p.lantern, 0x26),
    'coral_soft': alpha(p.coral, 0x2E),
    'cell_empty': cellEmpty,
    'cell_rest': cellRest,
    'cell_1': mix(cellEmpty, p.lantern, 0.28),
    'cell_2': mix(cellEmpty, p.lantern, 0.52),
    'cell_3': mix(cellEmpty, p.lantern, 0.76),
    'cell_4': p.lantern,
    'cell_future': alpha(cellRest, 0x70),
    'flame_out_core': mix(shoal, p.bone, 0.12),
  };
}

/// Every widget layout the launcher inflates. The `_preview` layouts are the
/// widget picker's thumbnails and stay in Midnight: the picker shows them
/// before any palette has been reported.
const _layouts = [
  'widget_dashboard_row',
  'widget_habit_dashboard',
  'widget_habit_heatmap',
  'widget_list_loading',
  'widget_quick_add',
  'widget_single_habit_streak',
  'widget_task_row',
  'widget_today_habits',
  'widget_today_row',
  'widget_today_tasks',
  'widget_weekly_recap',
];

String _hex(Color c) =>
    '#${c.toARGB32().toRadixString(16).padLeft(8, '0').toUpperCase()}';

void main() {
  test('widget palette variants', () {
    final colourNames = RegExp(r'<color name="tide_([a-z0-9_]+)">')
        .allMatches(File('$_res/values/colors.xml').readAsStringSync())
        .map((m) => m.group(1)!)
        .toSet();

    // Every colour a widget can reach must have a derivation, or a palette's
    // widget would silently keep a Midnight value.
    final derived = _widgetColours(_original).keys.toSet();
    expect(
      colourNames.difference(derived),
      isEmpty,
      reason: 'colors.xml has a tide_ colour with no rule in _widgetColours',
    );

    final drawableDir = Directory('$_res/drawable');
    final layoutDir = Directory('$_res/layout');

    // Clear the last run, so a removed palette or widget leaves nothing
    // behind.
    for (final dir in [drawableDir, layoutDir]) {
      for (final file in dir.listSync().whereType<File>()) {
        if (file.readAsStringSync().contains(_marker)) file.deleteSync();
      }
    }

    final drawables = drawableDir
        .listSync()
        .whereType<File>()
        .map((f) => f.uri.pathSegments.last)
        .where((n) => n.endsWith('.xml'))
        .map((n) => n.substring(0, n.length - 4))
        .where((n) => n.startsWith('widget_') || n.startsWith('ic_widget_'))
        .toSet();

    final palettes = TidePalettes.all.where((p) => !identical(p, _original));

    final values = StringBuffer()
      ..writeln('<?xml version="1.0" encoding="utf-8"?>')
      ..writeln('<!-- $_marker. Do not edit: see values/colors.xml. -->')
      ..writeln('<resources>');
    for (final palette in palettes) {
      values.writeln('    <!-- ${palette.name} -->');
      _widgetColours(palette).forEach((role, colour) {
        values.writeln(
          '    <color name="tide_${palette.id}_$role">${_hex(colour)}</color>',
        );
      });
    }
    values.writeln('</resources>');
    File('$_res/values/widget_palettes.xml').writeAsStringSync('$values');

    String retarget(String source, String id) => source
        .replaceAllMapped(
          RegExp(r'@color/tide_([a-z0-9_]+)'),
          (m) => '@color/tide_${id}_${m.group(1)}',
        )
        .replaceAllMapped(
          RegExp(r'@drawable/([a-z0-9_]+)'),
          (m) => drawables.contains(m.group(1))
              ? '@drawable/${m.group(1)}_$id'
              : m.group(0)!,
        );

    String stamp(String source) {
      final comment = '<!-- $_marker from the Midnight original. -->';
      if (!source.startsWith('<?xml')) return '$comment\n$source';
      final end = source.indexOf('?>') + 2;
      return '${source.substring(0, end)}\n$comment${source.substring(end)}';
    }

    for (final palette in palettes) {
      for (final name in drawables) {
        final source = File('$_res/drawable/$name.xml').readAsStringSync();
        File(
          '$_res/drawable/${name}_${palette.id}.xml',
        ).writeAsStringSync(stamp(retarget(source, palette.id)));
      }
      for (final name in _layouts) {
        final source = File('$_res/layout/$name.xml').readAsStringSync();
        File(
          '$_res/layout/${name}_${palette.id}.xml',
        ).writeAsStringSync(stamp(retarget(source, palette.id)));
      }
    }
  });
}
